# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZL8X1ycfOTTLd2brkoQ2L4FIVIdXnrWR
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df1=pd.read_csv("bottle.csv")
df1.head()

df1.isna().sum()



df1 = df1.replace(["NaN", "NULL", ""], np.nan)

df1.shape

df1.columns

df1.dropna(inplace=True)
df1.head()

df1.shape

df1.columns

df1.isna().sum()

y=df1["Salnty"]
y

x = df1.drop(["Cst_Cnt", "Btl_Cnt", "Sta_ID", "Depth_ID","Salnty","R_SALINITY","S_prec"], axis=1)

x.corrwith(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

x_train

y_train

x_test

y_test

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
ac=StandardScaler()
regressor=LinearRegression()
regressor.fit(x_train,y_train)

y_pred=regressor.predict(x_test)

regressor.score(x_train,y_train)

regressor.score(x_test,y_test)

py=sns.scatterplot(x="T_degC",y="Salnty",hue="Salnty",data=df1)
plt.show()

df={"y_pred":y_pred,"y_test":y_test}
d=pd.DataFrame(df)
d

