# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPFNvDprv35yhO9SyfXsn2CAf_Buq1Yx
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from mlxtend.plotting import plot_decision_regions

data=pd.read_csv("data-2.csv")
data.head()

x=data.drop(columns=["id","diagnosis"],axis=1)
y=data["diagnosis"]
x

y

from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

l.fit(y)

y=l.transform(y)
y=pd.DataFrame(y,columns=["diagnosis"])

x.corrwith(y["diagnosis"])

x.drop(x.columns[[4,8,9,11,14,15,16,17,18,19,30]],axis=1,inplace=True)

x.isna().sum()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)
x_train

x_test

lr=LogisticRegression(multi_class="multinomial")
lr.fit(x_train,y_train)

lr.score(x_test,y_test),lr.score(x_train,y_train)

y_pred=lr.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

confusion_matrix(y_test,y_pred)

from sklearn.tree import DecisionTreeClassifier
df=DecisionTreeClassifier(random_state=42)
df.fit(x_train,y_train)
df.score(x_test,y_test)

from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier(n_estimators=10)
rc.fit(x_train,y_train)
rc.score(x_test,y_test)

from sklearn.naive_bayes import GaussianNB
gm=GaussianNB()
gm.fit(x_train,y_train)
gm.score(x_test,y_test)

from sklearn.neighbors import  KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=5, metric = 'minkowski', p = 2)
kn.fit(x_train,y_train)
kn.score(x_test,y_test)

