# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZL8X1ycfOTTLd2brkoQ2L4FIVIdXnrWR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df=pd.read_csv("wine.csv")
df.head()
l=LabelEncoder()
df["type"]=l.fit_transform(df["type"])
df.head()

def classify(q):
  if q<=5:
    return 0
  elif q==6:
    return 1
  else:
    return 2
  return 3
df["quality_label"]=df["quality"].apply(classify)
df.head()

df.dropna(inplace=True)
df.isna().sum()

x=df.drop(["quality","quality_label","fixed acidity","citric acid","residual sugar","free sulfur dioxide","pH","sulphates","total sulfur dioxide"],axis=1)
x

y=df["quality_label"]
y.head()

x.corrwith(y)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)



from sklearn.linear_model import LogisticRegression
lc=LogisticRegression(random_state=42)
lc.fit(x_train,y_train)
lc.score(x_test,y_test)

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

rf = RandomForestClassifier(random_state=42,n_estimators=10)
rf.fit(x_train, y_train)
print("Random Forest Accuracy:", rf.score(x_test, y_test))

gb = GradientBoostingClassifier(random_state=42)
gb.fit(x_train, y_train)
print("Gradient Boosting Accuracy:", gb.score(x_test, y_test))
sc=SVC(kernel="rbf",random_state=42)
sc.fit(x_train,y_train,)
print("Accuracy of SVC",sc.score(x_test,y_test))
k=KNeighborsClassifier(n_neighbors=5,metric="minkowski")
k.fit(x_train,y_train)
print("Accuracy of KNN",k.score(x_test,y_test))
gn=GaussianNB()
gn.fit(x_train,y_train)
print("Acuuracy of GNB",gn.score(x_test,y_test))
dc=DecisionTreeClassifier(random_state=42)
dc.fit(x_train,y_train)
print("Accuracy of DC",dc.score(x_test,y_test))