# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZL8X1ycfOTTLd2brkoQ2L4FIVIdXnrWR
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df=pd.read_csv("weatherHistory.csv")
df.head()

df.columns

df.shape

df.isna().sum()

df.dropna(inplace=True)
df.shape

df.nunique()

y=df.iloc[:,4]
y.head()

x=df.drop(df.columns[[0,1,2,4,11]], axis=1)
x.head()

x.corrwith(y)

x.drop(x.columns[[3,2,4,5,6]],inplace=True,axis=1)

x.corrwith(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
x_train.head()

x_test.head()

y_train.head()

y_test.head()

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
regressor.score(x_train,y_train),regressor.score(x_test,y_test)

ax=sns.scatterplot(x="Temperature (C)",y="Apparent Temperature (C)",data=df)
plt.plot(x.iloc[:, 0], regressor.predict(x), color="red", linewidth=1)
plt.show()

y_pred=regressor.predict(x_test)
d1={"y_pred":y_pred,"y_test":y_test}
pd.DataFrame(d1)

from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

print(regressor.coef_)

print(regressor.intercept_)