# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZL8X1ycfOTTLd2brkoQ2L4FIVIdXnrWR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns

df=pd.read_csv("Iris.csv")
df.head()

x=df.iloc[:,1:-1]
x.head()

df.isna().sum()

sns.pairplot(data=df,hue="Species")

from sklearn.cluster import KMeans
wcss=[]
for i in range(2,21):
  km=KMeans(n_clusters=i,init="k-means++")
  km.fit(x)
  wcss.append(km.inertia_)

from matplotlib import markers
plt.figure(figsize=(10,5))
plt.plot([i for i in range (2,21)],wcss,marker="o")
plt.xlabel("Clusters")
plt.xticks([i for i in range(2,21)])
plt.ylabel("WCSS")
plt.grid()
plt.show()

km=KMeans(n_clusters=3)
labels=km.fit_predict(x)

from sklearn.metrics import silhouette_score
silhouette_score(x,labels)

df["predictions"]=labels

df.head(100)

sns.pairplot(data=df.drop(["Id","Species"],axis=1),hue="predictions")

custom={
    "Iris-setosa":2,
    "Iris-versicolor":0,
    "Iris-virginica":1

}
df["Encoded"]=df["Species"].map(custom)
df.head()

acc=0
df.shape[0]

for s,e in zip(df["predictions"],df["Encoded"]):
  if s==e:
    acc+=1
acc

print((acc/df.shape[0])*100)