# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZL8X1ycfOTTLd2brkoQ2L4FIVIdXnrWR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sns

df=pd.read_csv("train.csv")
df.head()
df.isna().sum()
df.drop(["Cabin"],axis=1,inplace=True)
df.isna().sum()
df.dropna(inplace=True)
df.isna().sum()
df.head()

df2=pd.read_csv("test.csv")
df2.isna().sum()
df2.drop(["Cabin","Name","Ticket","PassengerId"],axis=1,inplace=True)
df2.dropna(inplace=True)
df2.head()

x=df.drop(["PassengerId","Survived","Name"],axis=1)
x.head()



y=df["Survived"]
y.head()

from sklearn.preprocessing import LabelEncoder
li=LabelEncoder()
mi=LabelEncoder()
x["Embarked"]=li.fit_transform(x["Embarked"])
x["Sex"]=mi.fit_transform(x["Sex"])
x.drop(["Ticket"],axis=1,inplace=True)
x

df2["Embarked"]=li.transform(df2["Embarked"])
df2["Sex"]=mi.transform(df2["Sex"])

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
x_train

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

from sklearn.linear_model import LogisticRegression
l=LogisticRegression(random_state=42)
l.fit(x_train,y_train)
l.score(x_test,y_test)

from sklearn.ensemble import RandomForestClassifier
rc=RandomForestClassifier(n_estimators=10,random_state=42)
rc.fit(x_train,y_train)
rc.score(x_test,y_test)

from sklearn.svm import SVC
sc=SVC(kernel="rbf",gamma=2, C=1, random_state=12)
sc.fit(x_train,y_train)
sc.score(x_test,y_test)

from sklearn.svm import SVC
s=SVC(kernel="sigmoid",random_state=42)
s.fit(x_train,y_train)
s.score(x_test,y_test)

from sklearn.svm import SVC
s1=SVC(kernel="poly",random_state=42)
s1.fit(x_train,y_train)
s1.score(x_test,y_test)

from sklearn.tree import DecisionTreeClassifier
dc=DecisionTreeClassifier()
dc.fit(x_train,y_train)
dc.score(x_test,y_test)

from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=5)
kn.fit(x_train,y_train)
kn.score(x_test,y_test)

predictions=rc.predict(df2)
predictions

df2["Survived"]=predictions
df2